<?php
declare(strict_types=1); require_once __DIR__.'/../app/bootstrap.php'; require_once __DIR__.'/_auth.php';
require_once __DIR__.'/../app/rate-limit.php'; require_once __DIR__.'/../app/security.php';
if(!empty($_SESSION['admin_ok'])&&!empty($_SESSION['admin_user'])){header('Location: /admin/settings.php',true,303);exit;} header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0'); header('Pragma: no-cache');
$error=''; if(isset($_GET['logged_out']))$error='Anda sudah keluar dari sesi admin.'; if(isset($_GET['reset_sent']))$error='PIN baru sudah dikirim ke email admin. Periksa inbox atau folder spam.';
$raw=bin2hex(random_bytes(32));$nonce=$raw.'.'.hash_hmac('sha256',$raw,(string)$config['admin']['session_secret']);

if($_SERVER['REQUEST_METHOD']==='POST'){
$loginRl=rl_check('login',5,300,30); if(!$loginRl['allowed']){$error='Terlalu banyak percobaan login. Coba lagi dalam beberapa menit.';} else {$provided=(string)($_POST['login_csrf']??'');$parts=explode('.',$provided,2);$valid=count($parts)===2&&preg_match('/^[a-f0-9]{64}$/',$parts[0])===1&&preg_match('/^[a-f0-9]{64}$/',$parts[1])===1&&hash_equals($parts[1],hash_hmac('sha256',$parts[0],(string)$config['admin']['session_secret']));if(!$valid)$error='Form login tidak valid. Muat ulang halaman lalu coba lagi.';else{$u=trim((string)($_POST['username']??''));$pin=(string)($_POST['pin']??'');$ok=hash_equals((string)$config['admin']['username'],$u)&&preg_match('/^\d{6}$/',$pin)===1&&password_verify($pin,(string)$config['admin']['pin_hash']);if($ok){session_regenerate_id(true);$_SESSION=['admin_ok'=>true,'admin_user'=>$u,'admin_last_activity'=>time(),'csrf'=>bin2hex(random_bytes(32))];security_log('login_success');header('Location: /admin/settings.php',true,303);exit;}$error='Username atau PIN 6 digit salah. Periksa kembali data login.';security_log('login_failed');}}}
?><?php auth_head('Login'); auth_open('/','Kembali ke website'); ?><section><div><div>Pusat Admin</div><h1>Selamat datang<br>kembali</h1><p>Masuk untuk mengelola website Anda dengan mudah.</p></div><div><div>Masuk ke Administrator</div><?php if($error):?><div role="alert"><?=e($error)?></div><?php endif;?><form method="post" autocomplete="on"><input type="hidden" name="login_csrf" value="<?=e($nonce)?>"><label><span>Username</span><input name="username" autocomplete="username" placeholder="username admin" maxlength="64" required></label><label><span>PIN</span><div><input id="login-pin" type="password" name="pin" inputmode="numeric" pattern="[0-9]{6}" minlength="6" maxlength="6" autocomplete="current-password" placeholder="------" required></div></label><div role="note">Sesi Admin menggunakan cookie aman dan berakhir setelah periode tidak aktif.</div><button type="submit">Masuk</button><p role="status" aria-live="polite"></p></form><div><a href="/admin/forgot.php">Lupa PIN?</a></div></div></section><?php auth_close('© '.date('Y').' Administrator'); ?>